### ISSUE TITLE
Extension not published on mvn repository yet?

### ISSUE THREAD

**Issue by pierre-borckmans** [wso2-extensions/siddhi-store-redis#27]
**Description:**
It appears that the extension is not yet published on the new repository linked in the documentation? 
https://mvnrepository.com/artifact/io.siddhi.extension.store.redis/siddhi-store-redis/ -> 404

Thanks for looking at this!

**Comment by niveathika** [comment]
@pierre-borckmans Thank you for pointing this out. We had some issues in maven central syncing recently and currently working on resolving them. 

In the meantime, you can download the jar form the WSO2 public nexus 
http://maven.wso2.org/nexus/content/groups/wso2-public/io/siddhi/extension/store/redis/siddhi-store-redis/3.1.1/

**Comment by mohanvive** [comment]
We have raised this to maven central team in below jira.
https://issues.sonatype.org/browse/OSSRH-48087

**Comment by pierre-borckmans** [comment]
@niveathika Thanks for your answer! 
Yes I did figure out I could use the WSO2 nexus in the meantime.

**Comment by niveathika** [comment]
Closing as the latest release is synced to Maven central

**Comment by mohanvive** [comment]
Artifacts are now synced to maven central hence closing the issue.. 
https://repo1.maven.org/maven2/io/siddhi/
