### ISSUE TITLE
This extension should adapt redis which is running in cluster mode

### ISSUE THREAD

**Issue by yourgentlesmile** [wso2-extensions/siddhi-store-redis#9]
**Description:**
Hey,developer,I found this extension is't adaptable redis when it run in cluster mode 
Here is a problem when this extension try to put data to the redis
```redis.clients.jedis.exceptions.JedisMovedDataException: MOVED 1181 192.168.1.68:6001```

**Suggested Labels:**
feature

**Suggested Assignees:**
N/A
**Affected Product Version:**
N/A
**OS, DB, other environment details and versions:**    
N/A
**Steps to reproduce:**
N/A
**Related Issues:**
N/A

**Comment by AnuGayan** [comment]
This will be addressed by #18

**Comment by niveathika** [comment]
This feature is released in version [v2.0.0](https://github.com/wso2-extensions/siddhi-store-redis/releases/tag/v2.0.0)
